### ISSUE TITLE
Dashboard UI fix

### ISSUE THREAD

**Issue by alexbennycodes** [mickasmt/next-auth-roles-template#1]
Right now the dashboard is centered to screen
![image](https://github.com/mickasmt/next-auth-roles-template/assets/98402835/456f7778-042a-470a-a35b-bfd37d259385)

It should look like this
![image](https://github.com/mickasmt/next-auth-roles-template/assets/98402835/ded27fc7-6bfb-4fca-9cbb-62b255e3ebd2)

```class="container max-w-[1650px] px-0"``` removing this would fix it

**Comment by mickasmt** [comment]
Hi @alexbennycodes
Currently, this is not a design issue. I wanted to replicate the Stripe dashboard, which keeps the sidebar and the main content together. For me, it was better to set a max-width instead of using a full-screen layout. However, you can set it up on your own if that works better for you.
