### ISSUE TITLE
What is the difference between "next-auth-roles-template" and "next-saas-stripe-starter"

### ISSUE THREAD

**Issue by huzhanchi** [mickasmt/next-auth-roles-template#2]
Hi, mickasmt

Really thanks for your wonderfull job. It is really smiplified and good starter for me.
However, confusion as the question. Which one should I choose to use from the long-term maintaince perspective.

**Comment by mickasmt** [comment]
Hi, thank you so much! I appreciate it.
Currently, I am a bit busy, but I will continue to update and maintain all projects on the weekends. The setup file and the dashboard design with a sidebar from the next-auth-roles-template will soon be added to the stripe-starter. Shadcn said he is working on the collapsible sidebar, and I'm just waiting for it to be ready to update the dashboard. I will also upgrade to the next versions of Next.js.

Both projects will have the same design, so the only difference will be the management of subscriptions and payments in the stripe-starter. If you need SaaS payment, then stripe-starter will be good; otherwise, the auth-role-starter alone is sufficient.

**Comment by huzhanchi** [comment]
Really appreciate the work you have done, it saves me a lot of time, you
know although shadcn provide enough components, but as a beginner, a neat
and compact starter is really helpful

**Comment by abdellatif-laghjaj** [comment]
@mickasmt Niice my friend, i guess it will be great if you simply add the functionlaies in the next-auth-roles-template to the next-saas-stripe-starter and ofc keep in mind the payment gateways !! (i guess it would be perefct if integrate lemeon squezy !)

**Comment by mickasmt** [comment]
@huzhanchi Thank you very much for your comment! I'm glad to hear that you find the project useful.
Hi @abdellatif-laghjaj Don't worry. I'm currently working on it. Stay tuned for upcoming updates!
